import {activeRubric, total, scoreAttempt} from './model.mjs';
import {submissionQueue, teachingSignals, gradeLink, reviewedComments, helpRequests, reviewTotal, reviewTotalLabel} from './grading.mjs';
import {renderAssessmentExplanation} from '../connected/review-explanation.mjs';
import {solutionPreviews} from './rubric-studio.mjs';

const gradeEscape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;'}[c]));
const gradeButton = (action, text, attributes = '', primary = false) => `<button type="button" class="btn${primary ? ' primary' : ''}" data-action="${action}" ${attributes}>${text}</button>`;

export function renderGrade(state, ui) {
  const rubric = activeRubric(state);
  if (!rubric) return '<div class="empty-copy">Publish grading standards to begin. <a href="#/homework/1/standards">Open standards</a></div>';
  if (!ui.connected) return '<div class="empty-copy">Open the connected classroom to grade submitted work.</div>';
  const rows = submissionQueue(state, ui.gradeSearch || '');
  const row = rows.find(r => r.student.id === ui.gradeSid) || rows.find(r => !r.complete) || rows[0];
  const question = rubric.questions.find(q => q.id === ui.gradeQ) || rubric.questions.find(q => !row?.attempt.questions[q.id]?.skimmed) || rubric.questions[0];
  const owner = state.reviewAssignments?.[row?.attempt.id];
  const mine = owner?.userId === ui.actor?.id;

  const intro = `<div class="grade-heading"><div><h2>Grade submissions</h2><p>Review one student's final homework from start to finish.</p></div><a class="text-link" href="#/homework/1/teaching">Teaching insights →</a></div>`;
  const assignment = row ? `<div class="grade-assignment"><div><label for="grade-student">Student<select id="grade-student">${rows.map(r => `<option value="${gradeEscape(r.student.id)}" ${r === row ? 'selected' : ''}>${gradeEscape(r.student.name)} · ${r.complete ? 'Reviewed' : `${r.checked}/${r.count} checked`}</option>`).join('')}</select></label><span>${row.checked} of ${row.count} questions checked · submitted version ${row.attempt.revision}</span><output id="grade-total" class="grade-score" aria-live="polite">${reviewTotalLabel(reviewTotal(rubric, row.attempt, ui.gradeDrafts, ui.gradeAI, question.id))}</output></div><div class="actions"><span>${row.complete ? `Reviewed · ${scoreAttempt(rubric, row.attempt) ?? '—'} / ${rubric.questions.reduce((n, q) => n + total(q), 0)}` : owner ? `Assigned to ${mine ? 'you' : gradeEscape(owner.name)}` : 'Ready for review'}</span>${!row.complete ? owner ? mine ? gradeButton('grade-release', 'Release review', `data-attempt="${gradeEscape(row.attempt.id)}" ${ui.gradeBusy ? 'disabled' : ''}`) : '' : gradeButton('grade-claim', 'Start review', `data-attempt="${gradeEscape(row.attempt.id)}" ${ui.gradeBusy ? 'disabled' : ''}`, true) : (!owner || mine) ? gradeButton('grade-reopen', 'Reopen review', `data-attempt="${gradeEscape(row.attempt.id)}" ${ui.gradeBusy ? 'disabled' : ''}`) : ''}</div></div>` : '';
  const students = `<aside class="grade-students grade-question-list" aria-label="Questions in this submission"><h2>Questions</h2><p class="grade-list-caption">${row?.checked || 0} / ${rubric.questions.length} checked</p><nav>${rubric.questions.map((q, i) => `<a href="${gradeLink(q.id, row?.student.id)}" ${q.id === question.id ? 'aria-current="page"' : ''}><strong>Question ${i + 1}</strong><span>${gradeEscape(q.title)}</span><span>${row?.attempt.questions[q.id]?.skimmed ? '✓ Checked' : 'Needs review'}<small>${total(q)} pts</small></span></a>`).join('')}</nav></aside>`;
  if (!row) return `${intro}<p class="empty-copy">No final submissions yet. Practice work stays in Teaching until a student hands it in.</p>`;
  const {student, attempt} = row, review = attempt.questions[question.id], currentIndex = rows.indexOf(row);
  const draft = ui.gradeDrafts?.[`${attempt.id}:${question.id}`] || {};
  const readonly = !mine || row.complete || ui.gradeBusy;
  const pages = review?.pages || [], pageIndex = Math.min(ui.gradePage || 0, Math.max(0, pages.length - 1));
  const page = pages[pageIndex], url = attempt.pdf && ui.docURLs[attempt.pdf.id];
  const source = rubric.documents.solution, sourceUrl = source && ui.docURLs[source.id];
  const pdf = `<section class="grade-paper" aria-label="Final submitted work"><div class="grade-paper-toolbar"><div><h3>${gradeEscape(student.name)}</h3><small>Submitted version ${attempt.revision} · Question ${rubric.questions.indexOf(question) + 1}</small></div><div class="actions">${gradeButton('grade-page-prev', '‹', `aria-label="Previous mapped page" ${pageIndex === 0 ? 'disabled' : ''}`)}<span>Page ${page || '—'} <small>(${pageIndex + 1}/${pages.length || 0})</small></span>${gradeButton('grade-page-next', '›', `aria-label="Next mapped page" ${pageIndex >= pages.length - 1 ? 'disabled' : ''}`)}</div></div><div class="grade-pdf">${url && page ? `<iframe title="${gradeEscape(student.name)} final work, page ${page}" src="${gradeEscape(url)}#page=${page}&toolbar=0&view=FitH"></iframe>` : `<div class="empty-copy">${pages.length ? 'PDF unavailable. The original work must be inspected before grading.' : 'No pages mapped to this question.'}</div>`}</div><div class="grade-paper-links">${url ? `<a href="${gradeEscape(url)}#page=${page || 1}" target="_blank" rel="noopener">Open full PDF ↗</a>` : ''}${sourceUrl ? `<a href="${gradeEscape(sourceUrl)}#page=${question.solutionPages?.[0] || 1}" target="_blank" rel="noopener">Professor solution ↗</a>` : ''}</div><details class="grade-history"><summary>Revision history (${student.attempts.filter(a => a.version === rubric.id).length})</summary><p>Earlier feedback is context only. Grade the submitted version shown above.</p>${student.attempts.filter(a => a.version === rubric.id).map(a => `<div><span>Version ${a.revision} · ${a.final ? 'Submitted' : 'Practice'}${a.id === attempt.id ? ' · grading this version' : ''}</span>${a.pdf && ui.docURLs[a.pdf.id] ? `<a href="${gradeEscape(ui.docURLs[a.pdf.id])}#page=${a.questions[question.id]?.pages?.[0] || 1}" target="_blank" rel="noopener">View work ↗</a>` : ''}</div>`).join('')}</details></section>`;
  const criteria = question.criteria.map((c, index) => {
    const r = review?.results[c.id] || {}, saved = draft[c.id], value = saved?.band ?? (review?.skimmed || ui.gradeAI ? r.band : '') ?? '';
    const comments = reviewedComments(state, question.id, c.id);
    const guide = `<details class="grade-guide"><summary>Scoring guide and exceptions</summary>${c.bands.map(b => `<p><strong>${b.points} / ${c.max}</strong> · ${gradeEscape(b.label)}</p>`).join('')}${(c.patterns || []).map(p => `<p>${gradeEscape(p.definition)}</p><p><strong>Do not flag:</strong> ${gradeEscape(p.exclusions)}</p>`).join('')}${(c.sourceRefs || []).map(r => `<small>${gradeEscape(r.name)}, page ${r.page_index + 1}</small>`).join('')}</details>`;
    return `<section class="grade-item"><div class="grade-item-heading"><span class="grade-item-number" aria-hidden="true">${index + 1}</span><h3>${gradeEscape(c.label)}</h3><span>${c.max} pts</span></div>${c.description ? `<p class="grade-rule">${gradeEscape(c.description)}</p>` : ''}${guide}${r.unclear ? '<p class="grade-warning">Check readability in the PDF before choosing a score.</p>' : ''}${r.dispute?.status === 'open' ? `<div class="grade-warning"><strong>Student dispute</strong><p>${gradeEscape(r.dispute.message)}</p></div>` : ''}${ui.gradeAI ? `<div class="grade-evidence">${renderAssessmentExplanation(r, c)}</div>` : ''}<label>Score<select name="band:${gradeEscape(c.id)}" ${readonly ? 'disabled' : ''}><option value="">Choose an outcome</option>${c.bands.map(b => `<option value="${gradeEscape(b.id)}" ${b.id === value ? 'selected' : ''}>${b.points} / ${c.max} · ${gradeEscape(b.label)}</option>`).join('')}</select></label>${!readonly && comments.length ? `<label>Reuse a reviewed comment<select data-grade-comment="${gradeEscape(c.id)}"><option value="">Choose a comment</option>${comments.map(text => `<option value="${gradeEscape(text)}">${gradeEscape(text)}</option>`).join('')}</select></label>` : ''}<label>Review note<textarea name="reason:${gradeEscape(c.id)}" rows="2" placeholder="Explain a deduction or changed judgment" ${readonly ? 'disabled' : ''}>${gradeEscape(saved?.reason ?? r.reason ?? '')}</textarea></label>${r.dispute?.status === 'open' ? `<label>Dispute decision<select name="resolution:${gradeEscape(c.id)}" ${readonly ? 'disabled' : ''}><option value="">Choose a decision</option><option value="upheld" ${saved?.resolution === 'upheld' ? 'selected' : ''}>Deduction stands</option><option value="overturned" ${saved?.resolution === 'overturned' ? 'selected' : ''}>Correct the judgment</option></select></label>` : ''}</section>`;
  }).join('');
  const rubricPanel = `<section class="grade-rubric" aria-label="Question rubric"><div class="grade-rubric-title"><h2>Rubric</h2><span>Standard v${rubric.id}</span></div>${question.solutionCrops?.length ? solutionPreviews(question, source) : ''}<details class="grade-expectations"><summary>Expected work and accepted methods</summary><p>${gradeEscape(question.expected)}</p><p>${gradeEscape(question.alternatives)}</p></details><label class="grade-toggle"><input type="checkbox" id="grade-ai" ${ui.gradeAI ? 'checked' : ''}> Show AI suggestions</label><form id="grade-review-form" data-q="${gradeEscape(question.id)}" data-attempt="${gradeEscape(attempt.id)}" data-revision="${draft.reviewRevision ?? review?.questionReview?.revision ?? 0}">${criteria}<div class="grade-save">${row.complete ? `<p class="grade-checked">✓ Checked${review?.questionReview?.name ? ` by ${gradeEscape(review.questionReview.name)}` : ''}</p>` : `<label class="grade-toggle"><input type="checkbox" name="checkedWork" ${draft.checkedWork ? 'checked' : ''} ${readonly || !url || !pages.length ? 'disabled' : ''}> I checked the full answer, including unflagged work</label><button class="btn primary" type="submit" ${readonly || !url || !pages.length ? 'disabled' : ''}>${ui.gradeBusy ? 'Saving…' : rubric.questions.every(q => q.id === question.id || attempt.questions[q.id]?.skimmed) ? 'Complete review' : 'Save and next question'}</button>${!mine ? '<p>Start this submission’s review to save decisions.</p>' : ''}`}</div></form></section>`;
  return `${intro}${assignment}<div class="grade-layout">${students}${pdf}${rubricPanel}</div><footer class="grade-footer"><span>${currentIndex + 1} of ${rows.length} final submissions</span><nav aria-label="Move between students">${currentIndex > 0 ? `<a class="btn" href="${gradeLink(question.id, rows[currentIndex - 1].student.id)}">Previous student</a>` : ''}${currentIndex < rows.length - 1 ? `<a class="btn" href="${gradeLink(question.id, rows[currentIndex + 1].student.id)}">Next student</a>` : ''}</nav></footer>`;
}

export function renderTeaching(state, ui) {
  const questions = teachingSignals(state), requests = helpRequests(state);
  const help = `<section class="teaching-help"><div class="section-heading"><h3>Students asking for help</h3><span>${new Set(requests.map(h => h.student.id)).size} students</span></div>${requests.map(h => {
    const q = questions.find(q => q.id === h.questionId), url = h.attempt.pdf && ui.docURLs[h.attempt.pdf.id];
    return `<article><div><strong>${gradeEscape(h.student.name)}</strong><small>${gradeEscape(q?.title || h.questionId)} · version ${h.attempt.revision}</small><p>${gradeEscape(h.message || 'Would like to go through this question with a TA.')}</p>${url ? `<a href="${gradeEscape(url)}#page=${h.attempt.questions[h.questionId]?.pages?.[0] || 1}" target="_blank" rel="noopener">View original work ↗</a>` : ''}</div>${gradeButton('grade-help-resolve', 'Mark addressed', `data-help="${gradeEscape(h.id)}" ${ui.gradeBusy ? 'disabled' : ''}`)}</article>`;
  }).join('') || '<p>No open help requests.</p>'}</section>`;
  return `<section class="teaching-view"><div class="grade-heading"><div><h2>Teaching</h2><p>Use early difficulties to plan recitation and office hours.</p></div><a class="text-link" href="${gradeLink(questions[0]?.id || '')}">Return to grading</a></div><p class="teaching-note">Counts are distinct students per rubric item. A flag disappearing does not establish learning. Unassessed work is not counted as correct.</p>${help}${questions.map(q => `<section class="teaching-question"><div class="section-heading"><h3>${gradeEscape(q.title)}</h3><a href="${gradeLink(q.id)}">Grade question →</a></div><div class="table-wrap"><table><caption class="sr-only">${gradeEscape(q.title)} first-assessed and latest-attempt feedback</caption><thead><tr><th>Difficulty</th><th>First assessed</th><th>Still flagged</th><th>Absent in later work</th><th>TA corrected</th></tr></thead><tbody>${q.patterns.filter(p => p.initial || p.current || p.overturned).map(p => `<tr><th scope="row"><strong>${gradeEscape(p.label)}</strong><small>${gradeEscape(p.category || 'Course requirement')}</small><details><summary>Example work</summary>${p.examples.slice(0, 3).map(x => {
    const url = x.attempt.pdf && ui.docURLs[x.attempt.pdf.id];
    return `<div>${url ? `<a href="${gradeEscape(url)}#page=${x.attempt.questions[q.id]?.pages?.[0] || 1}" target="_blank" rel="noopener">${gradeEscape(x.name)} · version ${x.attempt.revision} ↗</a>` : gradeEscape(x.name)}</div>`;
  }).join('') || '<p>No first-attempt example available.</p>'}</details></th><td>${p.initial} <small>of ${p.assessed} assessed</small></td><td>${p.current}</td><td>${p.absentLater}</td><td>${p.overturned}</td></tr>`).join('') || '<tr><td colspan="5">No recorded difficulties for this question yet.</td></tr>'}</tbody></table></div></section>`).join('') || '<p class="empty-copy">Publish standards and collect feedback to see teaching signals.</p>'}</section>`;
}
