const rubricEscape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cropStyle = rect => `left:${rect[0]*100}%;top:${rect[1]*100}%;width:${rect[2]*100}%;height:${rect[3]*100}%`;
export function solutionPreviews(question, solution, {editable = false, qi = 0} = {}) {
  const crops = question.solutionCrops || [];
  return `<section class="solution-excerpts" aria-label="Solution excerpts"><div class="section-heading"><h3>Answer reference</h3><span class="staff-only">Staff only</span></div>${crops.length ? crops.map((crop, index) => {
    const stale = crop.documentId !== solution?.id || (solution?.pageCount && crop.page > solution.pageCount);
    return `<figure class="solution-excerpt ${stale ? 'stale-crop' : ''}">${stale ? '<p class="crop-stale">Solution PDF changed. Review and remap this excerpt.</p>' : `<div class="excerpt-image"><canvas data-reference-pdf="${rubricEscape(crop.documentId)}" data-page="${crop.page}" data-crop="${rubricEscape(JSON.stringify(crop.rect))}" aria-label="${rubricEscape(crop.label)}, solution page ${crop.page}"></canvas><p data-pdf-status role="status">Loading answer excerpt…</p></div>`}<figcaption><span><strong>${rubricEscape(crop.label || `Answer ${index + 1}`)}</strong><small>Solution page ${crop.page}</small></span>${editable ? `<div class="actions"><button class="btn crop-edit" data-action="edit-crop" data-q="${qi}" data-crop-id="${rubricEscape(crop.id)}">${stale ? 'Remap' : 'Edit'}</button><button class="icon-btn" data-action="remove-crop" data-q="${qi}" data-crop-id="${rubricEscape(crop.id)}" aria-label="Remove answer excerpt ${index + 1}">×</button></div>` : ''}</figcaption></figure>`;
  }).join('') : '<p class="quiet-note">Select part of the solution PDF to keep the correct answer beside this question.</p>'}${editable ? `<button class="btn" data-action="start-crop" ${!solution || crops.length >= 12 ? 'disabled' : ''}>+ Crop answer from PDF</button><p class="quiet-note crop-map-note">Add more than one excerpt if the answer spans pages. Student page assignments stay separate.</p>` : ''}</section>`;
}
export function cropSelectionEditor(ui) {
  if (!ui.cropSelection) return '';
  const selected = ui.cropSelection;
  return `<form id="crop-selection-form" class="crop-selection-editor"><div class="section-heading"><strong>${selected.id ? 'Edit answer excerpt' : 'New answer excerpt'}</strong><span>Page ${ui.setupPage || 1}</span></div><p>Drag on the PDF or adjust the bounds below.</p><label>Excerpt label<input name="label" maxlength="100" value="${rubricEscape(selected.label)}" placeholder="e.g. Final answer and reasoning"></label><div class="crop-bounds">${['Left','Top','Width','Height'].map((label,i) => `<label>${label} %<input type="number" min="${i > 1 ? .2 : 0}" max="100" step="0.1" name="bound${i}" data-crop-bound="${i}" value="${Math.round(selected.rect[i]*1000)/10}" required></label>`).join('')}</div><div class="actions"><button class="btn primary" type="submit">Save answer crop</button><button class="btn" type="button" data-action="cancel-crop">Cancel</button></div></form>`;
}
export function rubricDocument(s, ui) {
  const kind = ui.setupDoc || (s.documents.solution ? 'solution' : 'blank');
  const choices = [['solution','Solution PDF',s.documents.solution],['blank','Blank assignment',s.documents.blank],...s.documents.examples.map((doc,i)=>[`example-${i}`,`Graded example ${i+1}`,doc])];
  const doc = choices.find(([id]) => id === kind)?.[2];
  const page = ui.setupPage || 1, count = doc && (ui.pdfCounts?.[doc.id] || doc.pageCount);
  const q = s.draft[ui.editQ] || s.draft[0];
  const crops = kind === 'solution' ? (q?.solutionCrops || []).filter(c => c.documentId === doc?.id && c.page === page) : [];
  return `<section class="rubric-document" aria-label="Reference PDF"><div class="rubric-document-toolbar"><label class="sr-only" for="setup-document">Reference document</label><select id="setup-document">${choices.map(([id,label,document]) => `<option value="${id}" ${kind === id ? 'selected' : ''} ${document ? '' : 'disabled'}>${label}</option>`).join('')}</select><span class="staff-only">Private reference</span></div>${doc ? `<div class="rubric-view-tools"><div class="page-controls"><button class="btn" data-action="setup-prev" aria-label="Previous reference page" ${page <= 1 ? 'disabled' : ''}>‹</button><label class="sr-only" for="setup-page">Reference page</label><input id="setup-page" type="number" min="1" ${count ? `max="${count}"` : ''} value="${page}"><span data-pdf-page-count>of ${count || '…'}</span><button class="btn" data-action="setup-next" aria-label="Next reference page" ${!count || page >= count ? 'disabled' : ''}>›</button></div><div class="actions zoom-actions"><button class="icon-btn" data-action="setup-zoom-out" aria-label="Zoom out reference">−</button><span>${Math.round((ui.setupZoom || 1)*100)}%</span><button class="icon-btn" data-action="setup-zoom-in" aria-label="Zoom in reference">+</button><button class="btn ${ui.cropSelection ? 'active' : ''}" data-action="start-crop" ${kind !== 'solution' || !q ? 'disabled' : ''}>Crop answer</button></div></div><div class="rubric-pdf-scroll"><div class="crop-surface ${ui.cropSelection ? 'is-drawing' : ''}"><canvas data-reference-pdf="${rubricEscape(doc.id)}" data-page="${page}" data-zoom="${ui.setupZoom || 1}" aria-label="${rubricEscape(doc.name)}, page ${page}"></canvas><p data-pdf-status role="status">Loading PDF…</p><p class="sr-only" data-pdf-transcript></p>${crops.map((crop,i)=>`<div class="saved-crop" style="${cropStyle(crop.rect)}"><span>${rubricEscape(crop.label || `Answer ${i+1}`)}</span></div>`).join('')}<div class="crop-selection" ${ui.cropSelection ? `style="${cropStyle(ui.cropSelection.rect)}"` : 'hidden'}></div></div></div><div class="rubric-document-footer"><span>${ui.cropSelection ? 'Drag to select the answer, then save the crop.' : 'Select a question on the right to see its answer regions.'}</span><a href="${rubricEscape(ui.docURLs[doc.id] || '')}" target="_blank" rel="noopener">Open original</a></div>` : `<div class="rubric-pdf-empty"><span class="empty-pdf-icon" aria-hidden="true">▤</span><h3>Your solution, right here</h3><p>Attach the solution PDF to crop the answer for each question while you build its rubric.</p><label class="file-picker">Choose solution PDF<input type="file" accept="application/pdf,.pdf" data-file="solution" aria-label="Choose solution PDF"></label></div>`}</section>`;
}
export function renderRubricStudio(s, ui, {editor, upload, aiPanel}) {
  const qi = Math.min(ui.editQ, Math.max(0,s.draft.length-1)), q = s.draft[qi];
  const tab = ui.setupTab || 'rubric';
  return `<div class="standards-heading"><div><h2>Build your grading standard</h2><p>Keep the solution in view. Define the work you expect and what earns a deduction.</p></div>${!s.versions.length ? '<button class="btn" data-action="sample-rubric">Use sample materials</button>' : ''}</div><div class="rubric-studio">${rubricDocument(s,ui)}<aside class="rubric-sidebar" aria-label="Rubric authoring"><div class="studio-tabs" role="tablist" aria-label="Rubric setup">${[['rubric','Questions & deductions'],['references','Reference PDFs']].map(([id,label])=>`<button id="studio-tab-${id}" role="tab" aria-selected="${tab===id}" aria-controls="studio-panel-${id}" tabindex="${tab===id?0:-1}" data-action="setup-tab" data-tab="${id}">${label}</button>`).join('')}</div><section id="studio-panel-rubric" class="studio-tab-panel" role="tabpanel" aria-labelledby="studio-tab-rubric" ${tab!=='rubric'?'hidden':''}><div class="studio-question-nav"><label for="setup-question">Question<select id="setup-question">${s.draft.map((item,i)=>`<option value="${i}" ${qi===i?'selected':''}>${i+1}. ${rubricEscape(item.title)}</option>`).join('')}</select></label><button class="btn" data-action="add-question">+ Question</button></div>${q ? `${cropSelectionEditor(ui)}${editor(q,qi,ui,s.documents.solution)}` : '<div class="rubric-empty"><h3>Add your first question</h3><p>Give it a prompt, crop its solution, and add your deductions.</p><button class="btn primary" data-action="add-question">Add question</button></div>'}<label class="grading-instructions">General grading instructions<textarea rows="3" id="instructions">${rubricEscape(s.instructions)}</textarea></label></section><section id="studio-panel-references" class="studio-tab-panel" role="tabpanel" aria-labelledby="studio-tab-references" ${tab!=='references'?'hidden':''}>${upload(s,'blank','Blank assignment','The questions students receive.')}${upload(s,'solution','Professor solution','Private worked answers for you and your TAs.')}${upload(s,'examples','Past graded work','Optional examples of how you apply deductions.',true)}<p class="privacy-note">${ui.connected?'References are saved privately to your course. Only the published blank assignment is visible to students.':'PDFs stay in this browser unless you explicitly send them to the connected API.'}</p>${aiPanel(s,ui)}</section></aside></div><footer class="setup-footer"><span>${s.dirty?'Draft changes not finalized':s.versions.length?`Standard v${s.versions.at(-1).id} is ready`:'Review the draft before finalizing'}</span><button class="btn primary" data-action="publish" ${ui.busy||!s.draft.length||(!s.dirty&&s.versions.length)||ui.cropSelection?'disabled':''}>Finalize grading standard</button></footer>`;
}
