import {renderRubricStudio, solutionPreviews} from './rubric-studio.mjs';
import {activeRubric, analytics, total, latestFor, scoreAttempt, scoreQuestion} from './model.mjs';
import {renderCaseStudent} from './case-view.mjs';
import {renderAssessmentExplanation} from '../connected/review-explanation.mjs';
export const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'}[c]));
const e = escapeHTML;
const btn = (action, label, attrs = '', primary = false) => `<button type="button" class="btn${primary ? ' primary' : ''}" data-action="${action}" ${attrs}>${label}</button>`;
const badge = (text, type = '') => `<span class="badge ${type}">${e(text)}</span>`;
const percent = n => n === null ? '—' : `${n}%`;
const selected = (a, b) => a === b ? 'selected' : '';
const fmt = date => date ? new Date(date).toLocaleTimeString([], {hour: 'numeric', minute: '2-digit'}) : 'Not yet saved';
const icon = name => `<svg aria-hidden="true" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">${({book: '<path d="M4 4h6a3 3 0 0 1 3 3v14a4 4 0 0 0-4-2H4z"/><path d="M13 7a3 3 0 0 1 3-3h4v15h-4a4 4 0 0 0-3 2"/>', grid: '<rect x="4" y="4" width="6" height="6" rx="1"/><rect x="14" y="4" width="6" height="6" rx="1"/><rect x="4" y="14" width="6" height="6" rx="1"/><rect x="14" y="14" width="6" height="6" rx="1"/>', arrow: '<path d="M5 12h14m-5-5 5 5-5 5"/>', file: '<path d="M6 3h8l4 4v14H6zM14 3v5h4M9 12h6m-6 4h6"/>', chart: '<path d="M4 3v17h17M7 15l4-5 4 3 5-8"/>', check: '<path d="m5 12 4 4L19 6"/>'})[name] || ''}</svg>`;
export function routeFrom(hash) {
  if (hash.endsWith('/practice')) return 'practice';
  if (/\/review\//.test(hash)) return 'review';
  if (hash.endsWith('/standards')) return 'standards';
  if (hash.endsWith('/submissions')) return 'submissions';
  if (hash.endsWith('/activity')) return 'activity';
  return hash.includes('/homework/1') ? 'dashboard' : 'home';
}
function nav(s, ui) {
  if (ui.connected) return `<aside class="course-rail"><a class="brand" href="#/" aria-label="Verity home"><span class="brand-mark">v</span>verity</a><nav aria-label="Courses"><p class="rail-label">Your classes</p><a class="course-link" href="#/">${icon('book')}<span>${e(s.course)}</span></a><a class="rail-link" href="#/">${icon('grid')}Homework</a></nav><div class="rail-bottom"><p class="save-state">${e(ui.storageStatus)}</p></div></aside>`;
  return `<aside class="course-rail"><a class="brand" href="#/" aria-label="Verity home"><span class="brand-mark">v</span>verity</a><nav aria-label="Courses"><p class="rail-label">Your classes</p><a class="course-link" href="#/" aria-current="page">${icon('book')}<span>Linear Algebra<small>21-254</small></span></a><a class="rail-link" href="#/">${icon('grid')}Homework</a></nav><div class="rail-bottom"><label for="role">Preview role</label><select id="role"><option ${selected(s.role, 'Professor')}>Professor</option><option ${selected(s.role, 'TA')}>TA</option></select><small>Local preview, not authentication</small><p class="save-state ${ui.storageError ? 'warning-text' : ''}">${e(ui.storageStatus || 'Opening local workspace…')}</p>${btn('reset', 'Clear local workspace', '', false)}</div></aside>`;
}
function sectionTabs(page) {
  return `<nav class="section-tabs" aria-label="Homework sections">${[['dashboard', 'Overview', ''], ['standards', 'Rubric', '/standards'], ['submissions', 'Grading', '/submissions']].map(([id, label, path]) => `<a href="#/homework/1${path}" ${page === id || (page === 'review' && id === 'submissions') ? 'aria-current="page"' : ''}>${label}</a>`).join('')}</nav>`;
}
function header(s, page) {
  return `<header class="page-header"><a class="breadcrumb" href="#/">${e(s.courseCode || (s.course === 'Linear Algebra' ? '21-254 · Linear Algebra' : s.course))}</a><div class="heading-row"><h1>${page === 'home' ? 'Homework' : e(s.title)}</h1></div></header>${page !== 'home' ? sectionTabs(page) : ''}`;
}
function home(s) {
  const stats = analytics(s), rubric = activeRubric(s);
  return `<section class="home-list"><a class="homework-row" href="#/homework/1"><span class="homework-symbol">${icon('file')}</span><div><h2>${e(s.title)}</h2>${rubric ? `<p>${rubric.questions.length} questions · ${rubric.questions.reduce((n, q) => n + total(q), 0)} points</p>` : ''}</div><div class="homework-state">${stats.pending ? badge(`${stats.pending} to review`) : !rubric ? badge('Set up') : ''}<span>${icon('arrow')}</span></div></a></section>`;
}
function graph(stats) {
  const width = 720, height = 245, left = 48, right = 686, top = 16, bottom = 192;
  const x = i => stats.questions.length === 1 ? (left + right) / 2 : left + i * (right - left) / (stats.questions.length - 1);
  const y = n => bottom - n / 100 * (bottom - top);
  const series = [['first', 'First attempt', 'first'], ['latest', 'Latest attempt', 'latest']];
  return `<div class="chart-wrap"><svg class="question-chart" viewBox="0 0 ${width} ${height}" role="img" aria-labelledby="chart-title chart-description"><title id="chart-title">Average score by question</title><desc id="chart-description">Percent of question points. ${stats.questions.map((q, i) => `Question ${i + 1}: first ${percent(q.first)}, latest ${percent(q.latest)}, ${q.latestN} assessed students.`).join(' ')}</desc>${[0, 25, 50, 75, 100].map(n => `<line class="gridline" x1="${left}" x2="${right}" y1="${y(n)}" y2="${y(n)}"/><text class="axis-label" x="${left - 12}" y="${y(n) + 4}" text-anchor="end">${n}%</text>`).join('')}${series.map(([key, label, cls]) => {
    const segments = []; let points = [];
    for (const [i, q] of stats.questions.entries()) { if (q[key] === null) { if (points.length) segments.push(points.join(' ')); points = []; } else points.push(`${x(i)},${y(q[key])}`); }
    if (points.length) segments.push(points.join(' '));
    return segments.map(p => `<polyline class="series ${cls}" points="${p}"/>`).join('') + stats.questions.map((q, i) => q[key] === null ? '' : `<circle class="point ${cls}" cx="${x(i)}" cy="${y(q[key])}" r="5"><title>${e(label)}: ${q[key]}%</title></circle>`).join('');
  }).join('')}${!stats.questions.some(q => q.first !== null || q.latest !== null) ? '<rect class="chart-empty-backdrop" x="267" y="91" width="200" height="24"/><text class="chart-empty-label" x="367" y="108" text-anchor="middle">No graded submissions yet</text>' : ''}${stats.questions.map((q, i) => `<text class="axis-label" x="${x(i)}" y="${bottom + 28}" text-anchor="middle">Question ${i + 1}</text>`).join('')}</svg></div>`;
}
function dashboard(s, ui) {
  const rubric = activeRubric(s), stats = analytics(s);
  const q = stats.questions.find(q => q.id === ui.insightQ) || stats.questions[0];
  return `<div class="overview-top"><div class="overview-stats"><span><strong>${stats.students}</strong> students</span><span><strong>${stats.reviewed}/${stats.students}</strong> reviewed</span><a href="#/homework/1/submissions"><strong>${stats.disputes}</strong> open disputes</a></div>${!rubric ? '<a class="btn primary" href="#/homework/1/standards">Set up rubric</a>' : ''}</div>${stats.stale ? `<div class="notice warning">${stats.stale} submissions use an older rubric and are excluded here. ${btn('recheck', 'Prepare current-version reviews')}</div>` : ''}
    <section class="progress-section"><div class="section-heading"><h2>Scores by question</h2></div><div class="chart-legend"><span><i class="first-line"></i>First attempt</span><span><i class="latest-line"></i>Latest attempt</span></div>${graph(stats)}${stats.students ? `<div class="chart-footnote"><span>${s.demoLoaded ? 'Fictional demo records · ' : ''}Estimates until TA review</span></div>` : ''}${stats.questions.length ? `<div class="question-summary" role="group" aria-label="Inspect a question">${stats.questions.map((item, i) => `<button data-action="insight" data-q="${item.id}" aria-pressed="${q?.id === item.id}"><span>Question ${i + 1}</span><strong>${percent(item.latest)}</strong><small>${item.latestN} assessed · first ${percent(item.first)}</small></button>`).join('')}</div>` : ''}</section>
    ${q ? `<section class="pattern-section"><div class="section-heading"><h2>${e(q.title)}</h2></div><div class="table-wrap"><table><caption class="sr-only">Question-level issue counts</caption><thead><tr><th>Requirement</th><th>Initially flagged</th><th>Resolved</th><th>Unresolved</th><th>Disputed</th><th>Overturned</th></tr></thead><tbody>${q.patterns.map(p => `<tr><th scope="row">${e(p.label)}<small>${e(p.category)}</small></th><td>${p.initial}</td><td>${p.resolved}</td><td>${p.unresolved}</td><td>${p.disputed}</td><td>${p.overturned}</td></tr>`).join('')}</tbody></table></div>${stats.students ? '<p class="quiet-note">Resolved flags describe changes in submitted work, not proof of lasting learning. With one student, these are case details, not class-wide conclusions.</p>' : ''}</section>` : ''}`;
}
function upload(s, kind, title, description, optional = false) {
  const docs = kind === 'examples' ? s.documents.examples : [s.documents[kind]].filter(Boolean);
  return `<section class="material"><div class="section-heading"><h3>${title}</h3><span>${optional ? 'Optional' : 'Required'}</span></div><p>${description}</p>${docs.map((d, i) => `<div class="file-row">${icon('file')}<button type="button" class="file-title" data-action="pdf" data-kind="${kind}" data-index="${i}">${e(d.name)}<small>${d.sample ? 'Sample PDF' : d.remoteId ? 'Saved to course' : 'Stored in this browser'}${d.pageCount ? ` · ${d.pageCount} pages` : ''}</small></button><button class="icon-btn" data-action="remove-file" data-kind="${kind}" data-index="${i}" aria-label="Remove ${e(d.name)}">×</button></div>`).join('')}<label class="file-picker">${docs.length && !optional ? 'Replace PDF' : 'Choose PDF'}<input type="file" accept="application/pdf,.pdf" data-file="${kind}" ${optional ? 'multiple' : ''} aria-label="${title}"></label><small class="upload-limit">PDF, up to 20 MB${optional ? ' per file' : ''}</small></section>`;
}
function draftPanel(ui) {
  if (!ui.connected) return `<details class="api-panel" ${ui.apiOpen ? 'open' : ''}><summary>Connect AI rubric drafting</summary><p>Uses your existing grading backend. Requires a running worker, server-side AI credentials, and an instructor token. Scanned-PDF OCR is not enabled by this UI.</p><form id="api-form"><div class="api-fields"><label>API origin<input id="api-origin" type="url" value="${e(ui.apiOrigin)}" placeholder="http://localhost:8000"></label><label>Existing course ID<input id="api-course" value="${e(ui.apiCourse)}"></label><label>Staff access token<input id="api-token" type="password" autocomplete="off" value="${e(ui.apiToken)}"></label></div><label class="check-label"><input id="ai-consent" type="checkbox" ${ui.consent ? 'checked' : ''}>Upload these reference PDFs to my backend and allow it to send them to its configured AI provider.</label><p class="quiet-note">Creates a new server assignment and imports the generated rubric locally. It does not publish grades or rubrics to students. Tokens stay in memory.</p><div class="actions">${btn('test-api', 'Test connection', ui.busy ? 'disabled' : '')}<button class="btn" type="submit" ${ui.busy ? 'disabled' : ''}>Generate AI draft</button>${ui.busy ? btn('cancel-api', 'Stop waiting') : ''}</div></form><p class="api-progress" role="status">${e(ui.apiProgress || '')}</p></details>`;
  return `<section class="api-panel connected-drafting" aria-labelledby="draft-heading"><h3 id="draft-heading">Generate a rubric from your PDFs</h3><p>Uses the blank assignment, professor solution, grading guidelines, and past graded examples. Reviews all reference pages, including graphs and handwritten work.</p><p>Drafts explain what earns credit, when to deduct, and when a TA should check. Required formatting, missing graphs, and minor mistakes are distinguished from harmless style differences.</p><form id="api-form"><label class="check-label"><input id="ai-consent" type="checkbox" ${ui.consent ? 'checked' : ''} ${ui.busy ? 'disabled' : ''}>Allow this request to send the saved reference PDFs to the configured AI provider. This uses paid API credits.</label><p class="quiet-note">Instructor review is required before finalizing. Published standards and student grades stay unchanged. The server must be started with --allow-ai.</p><div class="actions"><button class="btn primary" type="submit" ${ui.busy ? 'disabled' : ''}>Generate AI draft</button>${ui.busy ? btn('cancel-api', 'Stop waiting') : ''}</div></form><p class="api-progress" role="status">${e(ui.apiProgress || '')}</p></section>`;
}
function criterionNotes(c) {
  const patterns = c.patterns || [], refs = c.sourceRefs || [];
  return `${patterns.length ? '<details class="rubric-notes"><summary>Error checks and exceptions</summary>' + patterns.map(p => '<p><strong>' + e(p.category) + '</strong> · ' + e(p.definition) + '</p><p><strong>Do not flag</strong> · ' + e(p.exclusions || 'Review valid alternatives against the requirement.') + '</p>').join('') + '</details>' : ''}${refs.length ? '<p class="rubric-sources"><strong>Source pages</strong><br>' + refs.map(r => e(r.name) + ', page ' + e(r.page_index + 1)).join('<br>') + '</p>' : ''}`;
}
function disclosure(ui, key) {
  return `data-disclosure="${e(key)}" ${ui.disclosures?.[key] ? 'open' : ''}`;
}
function criterion(c, ci, qi, ui) {
  return `<fieldset class="criterion compact-criterion"><legend class="sr-only">Rubric item ${ci + 1}</legend><div class="rubric-item-head"><span class="item-number">${ci + 1}</span><label class="item-points"><span class="sr-only">Max points</span><span aria-hidden="true">+</span><input aria-label="Points for rubric item ${ci + 1}" type="number" inputmode="decimal" min="0.01" max="1000" step="any" data-edit="criterion" data-q="${qi}" data-c="${ci}" data-field="max" value="${c.max}"></label><button class="icon-btn" data-action="remove-criterion" data-q="${qi}" data-c="${ci}" aria-label="Remove criterion ${ci + 1}">×</button></div><label class="item-description"><span class="sr-only">Requirement</span><textarea rows="1" placeholder="Describe what earns credit…" data-edit="criterion" data-q="${qi}" data-c="${ci}" data-field="label" maxlength="10000">${e(c.label)}</textarea></label><section class="item-deductions" aria-label="Deductions for rubric item ${ci + 1}">${c.bands.map((b, bi) => `<div class="outcome-row deduction-item ${ui.selectedDeductions?.has(`${qi}:${c.id}:${b.id}`) ? 'is-selected' : ''}" data-deduction-row="${e(`${qi}:${c.id}:${b.id}`)}"><button type="button" class="deduction-marker" aria-label="Select deduction ${bi + 1} in rubric item ${ci + 1} for editing" aria-pressed="${!!ui.selectedDeductions?.has(`${qi}:${c.id}:${b.id}`)}" data-row-number="${bi + 1}">${ui.selectedDeductions?.has(`${qi}:${c.id}:${b.id}`) ? '✓' : bi + 1}</button><label class="deduction-points"><span aria-hidden="true">−</span><input aria-label="Deduction for outcome ${bi + 1}, criterion ${ci + 1}" type="number" inputmode="decimal" min="0" max="${c.max}" step="any" data-edit="band" data-q="${qi}" data-c="${ci}" data-b="${bi}" data-field="deduction" value="${Math.round((c.max - b.points) * 100) / 100}"></label><textarea rows="1" aria-label="Criterion ${ci + 1}, outcome ${bi + 1}" placeholder="Describe this deduction…" data-edit="band" data-q="${qi}" data-c="${ci}" data-b="${bi}" data-field="label">${e(b.label)}</textarea></div>`).join('')}<div class="criterion-footer">${btn('add-band', '+ Add deduction', `data-q="${qi}" data-c="${ci}"`)}<details class="item-settings" ${disclosure(ui, `category-${c.id}`)}><summary>Item settings</summary><label>Issue category<input data-edit="criterion" data-q="${qi}" data-c="${ci}" data-field="category" value="${e(c.category)}" maxlength="100"></label>${criterionNotes(c)}</details></div></section></fieldset>`;
}
function editor(q, qi, ui, solution) {
  const stale = (q.solutionCrops || []).some(c => c.documentId !== solution?.id || c.page > solution?.pageCount);
  return `<section class="question-editor"><label class="question-description">Description<textarea placeholder="Briefly describe the question…" rows="2" data-edit="question" data-q="${qi}" data-field="prompt">${e(q.prompt)}</textarea></label><div class="rubric-items-heading"><h3>Total points</h3><strong data-question-total>${total(q)}</strong></div>${q.criteria.map((c, i) => criterion(c, i, qi, ui)).join('')}${btn('add-criterion', '+ Rubric item', `data-q="${qi}"`)}<div class="question-extras"><details class="question-reference" ${disclosure(ui, `refs-${q.id}`)}><summary>PDF reference <span>${stale ? 'Needs remapping' : q.solutionCrops?.length ? `${q.solutionCrops.length} excerpts` : `Page ${q.solutionPages.join(', ') || '—'}`}</span></summary>${solutionPreviews(q, solution, {editable: true, qi})}<div class="page-fields"><label>Blank PDF pages<input data-edit="question" data-q="${qi}" data-field="assignmentPages" value="${q.assignmentPages.join(', ')}" placeholder="1, 2"></label><label>Solution PDF pages<input data-edit="question" data-q="${qi}" data-field="solutionPages" value="${q.solutionPages.join(', ')}" placeholder="1, 2"></label></div></details><details class="question-settings" ${disclosure(ui, `settings-${q.id}`)}><summary>Question settings</summary><label>Question title<input data-edit="question" data-q="${qi}" data-field="title" value="${e(q.title)}" maxlength="100"></label><label>Expected work<textarea rows="2" data-edit="question" data-q="${qi}" data-field="expected">${e(q.expected)}</textarea></label><label>Accepted alternatives<textarea rows="2" data-edit="question" data-q="${qi}" data-field="alternatives">${e(q.alternatives)}</textarea></label><label>Assigned reviewer<input data-edit="question" data-q="${qi}" data-field="owner" value="${e(q.owner)}" maxlength="100"></label></details></div></section>`;
}
function rubricAISetup(s, ui) {
  return draftPanel(ui);
}
function standards(s, ui) {
  return renderRubricStudio(s, ui, {editor, upload, aiPanel: rubricAISetup});
}

function queue(s, ui) {
  const rubric = activeRubric(s); if (!rubric) return '<div class="empty-copy">Finalize a grading standard before reviewing work. <a href="#/homework/1/standards">Open setup</a></div>';
  let students = s.submissions.map(st => { const a = latestFor(st, rubric.id); const flags = a ? Object.values(a.questions).flatMap(q => Object.values(q.results)) : []; return {st, a, disputes: flags.filter(r => r.dispute?.status === 'open').length, unclear: flags.filter(r => r.unclear || !r.band).length}; });
  students = students.filter(({st, a, disputes, unclear}) => st.name.toLowerCase().includes(ui.search.toLowerCase()) && (ui.filter === 'all' || ui.filter === 'pending' && !a?.reviewedAt || ui.filter === 'disputes' && disputes || ui.filter === 'unclear' && unclear || ui.filter === 'reviewed' && a?.reviewedAt));
  students.sort((a, b) => (b.disputes * 10 + b.unclear) - (a.disputes * 10 + a.unclear));
  return `<div class="section-heading queue-heading"><div><h2>Grading</h2></div>${s.demoLoaded ? badge('Fictional demo work') : ''}</div><div class="queue-tools"><label>Find student<input id="search" type="search" value="${e(ui.search)}" placeholder="Search students"></label><label>Show<select id="filter">${[['all', 'All submissions'], ['pending', 'Needs review'], ['disputes', 'Student disputes'], ['unclear', 'Unclear work'], ['reviewed', 'Reviewed']].map(([v, label]) => `<option value="${v}" ${selected(ui.filter, v)}>${label}</option>`).join('')}</select></label><span>${students.length} shown</span></div><div class="table-wrap"><table class="submission-table"><thead><tr><th>Student</th><th>Latest attempt</th><th>Score</th><th>Review status</th><th></th></tr></thead><tbody>${students.map(({st, a, disputes, unclear}) => `<tr><th scope="row">${e(st.name)}<small>${a ? `Standard v${a.version}` : 'Older standard'}</small></th><td>${a ? `Version ${a.revision}` : '—'}</td><td>${a && scoreAttempt(rubric, a) !== null ? `${scoreAttempt(rubric, a)} / ${rubric.questions.reduce((n, q) => n + total(q), 0)}` : 'Unresolved'}<small>${a?.assessmentSource === 'professor-import' ? 'Imported professor grade' : a?.assessmentSource === 'ai-recorded' ? 'Recorded AI · provisional' : a?.reviewedAt ? 'TA reviewed' : 'Provisional'}</small></td><td>${badge(!a ? 'Recheck needed' : a.reviewedAt ? 'Reviewed' : disputes ? `${disputes} dispute${disputes > 1 ? 's' : ''}` : unclear ? 'Unclear work' : 'Needs skim', a?.reviewedAt ? 'success' : disputes || unclear ? 'warning' : '')}</td><td>${a ? `<a class="btn" href="#/homework/1/review/${st.id}">Review ${icon('arrow')}</a>` : btn('recheck', 'Prepare review')}</td></tr>`).join('') || '<tr><td colspan="5"><div class="empty-copy">No matching submissions.</div></td></tr>'}</tbody></table></div>`;
}
function viewer(s, ui, rubric, attempt, q, qreview) {
  const material = ui.doc === 'blank' ? rubric.documents.blank : ui.doc === 'solution' ? rubric.documents.solution : ui.doc === 'example' ? rubric.documents.examples[0] : attempt.pdf || null;
  const pages = ui.doc === 'student' ? qreview?.pages || [] : material ? ui.doc === 'blank' ? q.assignmentPages : ui.doc === 'solution' ? q.solutionPages : [1] : [];
  const page = pages[Math.min(ui.page, pages.length - 1)] || 1;
  const url = material && ui.docURLs[material.id];
  return `<section class="document-panel"><div class="document-controls"><label>Document<select id="document-kind"><option value="student" ${selected(ui.doc, 'student')}>Student work</option><option value="blank" ${selected(ui.doc, 'blank')}>Blank assignment</option><option value="solution" ${selected(ui.doc, 'solution')}>Professor solution</option>${rubric.documents.examples.length ? `<option value="example" ${selected(ui.doc, 'example')}>Past graded example</option>` : ''}</select></label><div class="page-controls">${btn('previous-page', '‹', `aria-label="Previous mapped page" ${ui.page <= 0 ? 'disabled' : ''}`)}<span>Page ${page}</span>${btn('next-page', '›', `aria-label="Next mapped page" ${ui.page >= pages.length - 1 ? 'disabled' : ''}`)}</div></div><div class="paper-canvas">${material ? url ? `<iframe title="${e(material.name)}, page ${page}" src="${e(url)}#page=${page}&toolbar=0"></iframe><a class="pdf-fallback" href="${e(url)}#page=${page}" target="_blank" rel="noopener">Open reference PDF</a>` : '<p class="empty-copy">Reference unavailable. Reattach its PDF in setup.</p>' : `<article class="sample-paper"><header><span>${e(s.title)}</span><span>Attempt ${attempt.revision}</span></header><h2>${e(q.title)}</h2><p class="paper-prompt">${e(q.prompt)}</p><pre class="sample-work">${e(qreview?.work || 'No work mapped to this question. Review the student page assignment.')}</pre><footer>Fictional demo work · typeset for this preview</footer></article>`}</div><div class="document-footer">${ui.doc === 'student' ? 'Student-assigned pages' : 'Teacher reference pages'}: ${pages.join(', ') || 'Not assigned'}. Reference and student mappings are independent.</div></section>`;
}
function review(s, ui) {
  const rubric = activeRubric(s), student = s.submissions.find(st => st.id === ui.sid), current = rubric && student && latestFor(student, rubric.id);
  if (!current) return '<div class="empty-copy">No review is available under this standard. <a href="#/homework/1/submissions">Return to the queue</a></div>';
  const eligible = student.attempts.filter(a => a.version === rubric.id), attempt = eligible.find(a => a.id === ui.attempt) || current;
  const q = rubric.questions.find(q => q.id === ui.reviewQ) || rubric.questions[0], qr = attempt.questions[q.id];
  const readOnly = attempt !== current || !!current.reviewedAt;
  return `<div class="review-top"><div><a class="breadcrumb" href="#/homework/1/submissions">‹ Review queue</a><h2>${e(student.name)}</h2></div><label>Submission version<select id="attempt">${eligible.map(a => `<option value="${e(a.id)}" ${selected(a.id, attempt.id)}>Attempt ${a.revision}${a.id === current.id ? ' (latest)' : ''}${a.reviewedAt ? ' · reviewed' : ''}</option>`).join('')}</select></label><div class="review-total"><span>${current.reviewedAt ? 'Reviewed score' : 'Proposed score'}</span><strong>${scoreAttempt(rubric, attempt) ?? '—'}<small> / ${rubric.questions.reduce((n, q) => n + total(q), 0)}</small></strong></div></div><div class="review-question-tabs" role="group" aria-label="Review question">${rubric.questions.map((item, i) => `<button data-action="review-question" data-q="${item.id}" aria-pressed="${q.id === item.id}"><span>Question ${i + 1}</span><strong>${scoreQuestion(item, attempt.questions[item.id]) ?? '—'} / ${total(item)}</strong><small>${attempt.questions[item.id]?.skimmed ? 'Checked' : e(item.owner)}</small></button>`).join('')}</div>${attempt !== current ? '<div class="notice">Viewing a previous attempt. Select the latest attempt to make review decisions.</div>' : ''}<div class="review-layout">${viewer(s, ui, rubric, attempt, q, qr)}<section class="review-rubric"><div class="section-heading"><h2>Question review</h2>${badge(qr?.skimmed ? 'Skim complete' : 'Needs skim', qr?.skimmed ? 'success' : '')}</div>${solutionPreviews(q, rubric.documents.solution)}<details class="expectations"><summary>Expected work and accepted alternatives</summary><p>${e(q.expected)}</p><p>${e(q.alternatives)}</p></details>${q.criteria.map(c => {
    const r = qr?.results[c.id] || {}, chosen = c.bands.find(b => b.id === r.band), proposed = c.bands.find(b => b.id === r.proposed);
    return `<section class="review-criterion"><div class="section-heading"><h3>${e(c.label)}</h3><strong>${chosen ? chosen.points : '—'} / ${c.max}</strong></div>${r.dispute ? `<div class="dispute"><strong>${r.dispute.status === 'open' ? 'Student thinks the AI is wrong' : `Dispute ${e(r.dispute.status)}`}</strong><p>${e(r.dispute.message)}</p>${r.dispute.resolution ? `<p>Response: ${e(r.dispute.resolution)}</p>` : ''}</div>` : ''}${r.unclear ? '<p class="warning-text">Unclear work. Resolve this manually before completing the skim.</p>' : ''}${renderAssessmentExplanation(r, c)}${r.proposed && r.band !== r.proposed ? `<small>Original proposal: ${proposed?.points ?? '—'} / ${c.max}</small>` : ''}${criterionNotes(c)}<form class="decision-form" data-q="${q.id}" data-c="${c.id}"><label>Scoring outcome<select name="band" ${readOnly ? 'disabled' : ''}><option value="" ${!r.band ? 'selected' : ''}>Needs a decision</option>${c.bands.map(b => `<option value="${e(b.id)}" ${selected(r.band, b.id)}>${/^\d+(?:\.\d+)?\s*\/\s*\d+(?:\.\d+)?\s*points?$/.test(b.label) ? `${b.points} / ${c.max} points` : `${e(b.label)} (${b.points}/${c.max})`}</option>`).join('')}</select></label><label>TA reasoning<textarea name="reason" rows="2" placeholder="Briefly explain the error or your score change" ${readOnly ? 'disabled' : ''}>${e(r.reason)}</textarea></label>${r.dispute?.status === 'open' ? '<label>Dispute decision<select name="resolution"><option value="">Choose a decision</option><option value="upheld">Original deduction is valid</option><option value="overturned">Student is right; correct the judgment</option></select></label>' : ''}<button class="btn" type="submit" ${readOnly ? 'disabled' : ''}>Save decision</button></form></section>`;
  }).join('')}<div class="skim-action">${btn('skim', qr?.skimmed ? 'Question checked' : 'I skimmed this question', `data-q="${q.id}" ${readOnly || qr?.skimmed ? 'disabled' : ''}`, true)}<p>Check the full work, including unflagged parts.</p></div></section></div><footer class="review-footer"><span>${current.reviewedAt ? `Reviewed at ${fmt(current.reviewedAt)}` : 'Complete a skim of every question before saving the reviewed grade.'}</span><div class="actions">${current.reviewedAt ? btn('reopen', 'Reopen review') : btn('complete', 'Complete review', attempt !== current ? 'disabled' : '', true)}</div></footer>`;
}
function activity(s) {
  return `<section class="activity-section"><h2>Grading history</h2><p>Rubric versions and reviewer decisions stay attributable. Local records only.</p>${s.log.length ? `<ol class="activity-list">${s.log.toReversed().map(item => `<li><time datetime="${e(item.at)}">${fmt(item.at)}</time><div><h3>${e(item.action)}</h3><p>${e(item.detail)}</p><small>${e(item.actor)}</small></div></li>`).join('')}</ol>` : '<p class="empty-copy">Your setup and review actions will appear here.</p>'}</section>`;
}
export function renderWorkspace(s, ui) {
  const studioHeader = `<header class="rubric-page-header"><a href="#/homework/1" aria-label="Back to homework">‹ ${e(s.title)}</a><h1>Rubric</h1><span class="save-state">${e(ui.storageStatus)}</span>${btn('publish', 'Publish rubric', ui.busy || !s.draft.length || (!s.dirty && s.versions.length) || ui.cropSelection ? 'disabled' : '', true)}</header>`;
  return `${ui.route === 'standards' ? '' : nav(s, ui)}<main id="main" tabindex="-1">${ui.route === 'standards' ? studioHeader + sectionTabs(ui.route) : header(s, ui.route)}${ui.error ? `<div class="notice error" role="alert">${e(ui.error)}</div>` : ''}${ui.message ? `<div class="notice" role="status">${e(ui.message)}</div>` : ''}${ui.storageError ? `<div class="notice warning">${e(ui.storageError)}</div>` : ''}<div class="page-content">${({home, dashboard, standards, submissions: queue, review, activity, practice: renderCaseStudent}[ui.route] || home)(s, ui)}</div></main>`;
}
